# docker-compose.yml
version: '3'
services:
  pysym:
    build:
      context: .
      dockerfile: Dockerfile
    image: ciscn/pysym
    ports:
      - "8080:1337"
    volumes:
      - .:/srv
    user: "1000"
