version: '3'
services:
  web:
    build: .
    volumes:
      - .:/var/www/html
    ports:
      - "8080:80"
    depends_on:
      - db
    environment:
      - APACHE_RUN_USER=#www-data
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=some_password
      - MYSQL_DATABASE=dolphin
      - MYSQL_USER=dolphin_user
      - MYSQL_PASSWORD=dolphin_password
volumes:
  db_data: {}
